_target_: src.scenario.GameScenario

policy: ~ policy
portfolio_critic: ~ portfolio_critic
market_critic: ~ market_critic
simulator: ~ simulator
portfolio_running_objective_model: 
  _target_: src.objective.PortfolioRunningObjectiveModel
  weights: = regelum.utils.rg.array([1.0] + [0.1]*${common.number_of_stocks}+[0.0]*(${common.number_of_stocks} * ( ${common.number_of_stocks} + 3 ) // 2 ))
market_running_objective_model:
  _target_: src.objective.MarketRunningObjectiveModel
  weights: = regelum.utils.rg.array([1.0] + [0.0]*(${common.number_of_stocks} * ( ${common.number_of_stocks} + 5 ) // 2 ))
discount_factor: $ common.discount_factor
sampling_time: $ common.sampling_time
N_iterations: 1
iters_to_switch_opt_agent: 2










